// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fdHQDRX6fW2LfqNOM4y4yULkCQNcPuM',
    appId: '1:137444147675:web:64542ae799b5578da927fe',
    messagingSenderId: '137444147675',
    projectId: 'zetaton-wallpaper',
    authDomain: 'zetaton-wallpaper.firebaseapp.com',
    storageBucket: 'zetaton-wallpaper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmQ0IZpYsqcRUcdANYcFuI5Q7PXLS0i4',
    appId: '1:137444147675:android:fe37853bfcbb5e4ea927fe',
    messagingSenderId: '137444147675',
    projectId: 'zetaton-wallpaper',
    storageBucket: 'zetaton-wallpaper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQSk_r8wdpf0_4cYDizCuAFIhww2A-RKQ',
    appId: '1:137444147675:ios:3f1be17636b3f9e7a927fe',
    messagingSenderId: '137444147675',
    projectId: 'zetaton-wallpaper',
    storageBucket: 'zetaton-wallpaper.appspot.com',
    iosBundleId: 'com.VE.zetatonWallpaper',
  );
}
